### ISSUE TITLE
`click` missing in GitHub action

### ISSUE THREAD

**Issue by akaihola** [akaihola/graylint#42]
From [job #145](https://github.com/akaihola/graylint/actions/runs/10145994148/job/28053022186?pr=40):
```python
Prepare all required actions
Getting action download info
Download action repository 'akaihola/darker@1.7.1' (SHA:959cc56abda18d90fee9e900aee52417b98a07f3)
Run ./
Run akaihola/darker/.github/actions/commit-range@1.7.1
Run if [ "${GITHUB_EVENT_NAME}" == "push" ]
 COMMIT_RANGE =  
Run # Exists since using github.action_path + path to main script doesn't
Defaulting to user installation because normal site-packages is not writeable
Collecting pip-requirements-parser
  Downloading pip_requirements_parser-32.0.1-py3-none-any.whl (35 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from pip-requirements-parser) (24.1)
Requirement already satisfied: pyparsing in /usr/lib/python3/dist-packages (from pip-requirements-parser) (2.4.7)
Installing collected packages: pip-requirements-parser
Successfully installed pip-requirements-parser-32.0.1
Collecting graylint[color]
  Cloning https://github.com/akaihola/graylint (to revision config-dump-section) to /tmp/pip-install-w875h66p/graylint_3c4c9b2d187c46b8b7a4ce252690ae7d
  Running command git clone --filter=blob:none --quiet https://github.com/akaihola/graylint /tmp/pip-install-w875h66p/graylint_3c4c9b2d187c46b8b7a4ce252690ae7d
  Running command git checkout -b config-dump-section --track origin/config-dump-section
  Switched to a new branch 'config-dump-section'
  branch 'config-dump-section' set up to track 'origin/config-dump-section'.
  Resolved https://github.com/akaihola/graylint to commit 71cf2f6f931f091ca763639903a200249d959587
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting flake8
  Downloading flake8-7.1.0-py2.py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 KB 4.5 MB/s eta 0:00:00
Collecting darkgraylib~=1.3.0
  Downloading darkgraylib-1.3.0-py3-none-any.whl (32 kB)
Collecting Pygments>=2.4.0
  Downloading pygments-2.18.0-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 45.8 MB/s eta 0:00:00
Collecting pyflakes<3.3.0,>=3.2.0
  Downloading pyflakes-3.2.0-py2.py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 KB 25.4 MB/s eta 0:00:00
Collecting pycodestyle<2.13.0,>=2.12.0
  Downloading pycodestyle-2.12.0-py2.py3-none-any.whl (31 kB)
Collecting mccabe<0.8.0,>=0.7.0
  Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Collecting toml>=0.10.0
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Building wheels for collected packages: graylint
  Building wheel for graylint (pyproject.toml): started
  Building wheel for graylint (pyproject.toml): finished with status 'done'
  Created wheel for graylint: filename=graylint-1.1.1-py3-none-any.whl size=26167 sha256=c46002843453afb6df5d68b0d353671dff23a2af6d3d7c7a4ad9fb6b8e3835f0
  Stored in directory: /tmp/pip-ephem-wheel-cache-3ws8fyw6/wheels/59/7b/73/798549b5353651c62f5687c20eab3a5d58ab22332f4355ec78
Successfully built graylint
Installing collected packages: toml, Pygments, pyflakes, pycodestyle, mccabe, flake8, darkgraylib, graylint
Successfully installed Pygments-2.18.0 darkgraylib-1.3.0 flake8-7.1.0 graylint-1.1.1 mccabe-0.7.0 pycodestyle-2.12.0 pyflakes-3.2.0 toml-0.10.2
Traceback (most recent call last):
  File "/home/runner/work/graylint/graylint/.graylint-env/bin/graylint", line 5, in <module>
    from graylint.__main__ import main_with_error_handling
  File "/home/runner/work/graylint/graylint/.graylint-env/lib/python3.10/site-packages/graylint/__main__.py", line 9, in <module>
    from darkgraylib.command_line import parse_command_line
  File "/home/runner/work/graylint/graylint/.graylint-env/lib/python3.10/site-packages/darkgraylib/command_line.py", line 18, in <module>
    from darkgraylib.config import (
  File "/home/runner/work/graylint/graylint/.graylint-env/lib/python3.10/site-packages/darkgraylib/config.py", line 10, in <module>
    import click
ModuleNotFoundError: No module named 'click'
Error: Process completed with exit code 1.
```

**Comment by akaihola** [comment]
Fixed in akaihola/darkgraylib#68 and the Darkgraylib upgrade in #41.
